; Polybar colors for Pywal v3.3.0
; This template is built line-by-line to avoid errors.

[colors]
background = {background}
background-alt = #99{color0.strip}
foreground = {foreground}
primary = {color4}
secondary = {color6}
alert = {color1}
disabled = #707880

; For transparency. 'dd' is the alpha value.
bg-transparent = #dd{background.strip}
