; Polybar colors for Pywal v3.3.0
; This template is built line-by-line to avoid errors.

[colors]
background = #10111e
background-alt = #9910111e
foreground = #d5ace0
primary = #5F5094
secondary = #E46A97
alert = #534776
disabled = #707880

; For transparency. 'dd' is the alpha value.
bg-transparent = #dd10111e
